<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.Net.ClientFactory" Version="2.76.0" />
		<PackageReference Include="Google.Protobuf" Version="3.33.2" />
		<PackageReference Include="Grpc.Tools" Version="2.76.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Confluent.Kafka" Version="2.12.0" />
		<PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
		<PackageReference Include="prometheus-net.SystemMetrics" Version="3.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AuthService.Protos\AuthService.Protos.csproj" />
	  <ProjectReference Include="..\Common\Common.csproj" />
	  <ProjectReference Include="..\ProgressService.Domain\ProgressService.Domain.csproj" />
	</ItemGroup>

</Project>
