syntax = "proto3";

import "google/protobuf/empty.proto"; 

option csharp_namespace = "EmailService.Protos";

package email;

service EmailApi {
  rpc SendCode (SendCodeRequest) returns (SendCodeResponse);
  rpc VerifyEmail (VerifyEmailRequest) returns (VerifyEmailResponse);
  rpc AddVerification (AddVerificationRequest) returns (google.protobuf.Empty);
  rpc VerifyChangedEmail (VerifyChangedEmailRequest) returns (google.protobuf.Empty);
}

// Requests
message SendCodeRequest {
  string email = 1;
  string code = 2;
}

message VerifyEmailRequest {
  string email = 1;
  string code = 2;
}

message AddVerificationRequest {
  string code = 1;
  optional string userid = 2;
  optional string username = 3;
  string useremail = 4;
  optional string userpassword = 5;
}

message VerifyChangedEmailRequest {
  string email = 1;
  string code = 2;
}

// Responses
message SendCodeResponse {
  string msg = 1;
}

message VerifyEmailResponse {
  string msg = 1;
}