<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.2.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
	<PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\SearchService.Domain\SearchService.Domain.csproj" />
  </ItemGroup>

</Project>
