<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
	  <PackageReference Include="prometheus-net.SystemMetrics" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\TestsService.Application\TestsService.Application.csproj" />
	<ProjectReference Include="..\TestsService.Infrastructure\TestsService.Infrastructure.csproj" />
    <ProjectReference Include="..\TestsService.Domain\TestsService.Domain.csproj" />
  </ItemGroup>

</Project>
