<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\LecturesService.Application\LecturesService.Application.csproj" />
    <ProjectReference Include="..\LecturesService.Domain\LecturesService.Domain.csproj" />
    <ProjectReference Include="..\LecturesService.Infrastructure\LecturesService.Infrastructure.csproj" />
    <ProjectReference Include="..\LecturesService.Protos\LecturesService.Protos.csproj" />
  </ItemGroup>

</Project>
