syntax = "proto3";

import "google/protobuf/empty.proto"; 

option csharp_namespace = "LecturesService.Protos";

package lectures;

service LecturesApi {
  rpc GetLectureById (GetLectureByIdRequest) returns (LectureResponse);
  rpc DeleteLecturesByCourseId (DeleteLecturesByCourseIdRequest) returns (google.protobuf.Empty);
}

// Requests
message GetLectureByIdRequest {
  string id = 1;
}

message DeleteLecturesByCourseIdRequest {
  string courseId = 1;
  string userId = 2;
}

// Responses
message LectureResponse {
  string id = 1;
  string name = 2;
  string content = 3;
  string courseId = 4;
  string authorId = 5;
}