syntax = "proto3";

import "google/protobuf/empty.proto"; 

option csharp_namespace = "AuthService.Protos";

package auth;

service AuthApi {
  rpc AddUser (AddUserRequest) returns (google.protobuf.Empty);
  rpc ChangeEmail (ChangeEmailRequest) returns (google.protobuf.Empty);
  rpc EditBalance (EditBalanceRequest) returns (google.protobuf.Empty);
}

// Requests
message AddUserRequest {
  string name = 1;
  string email = 2;
  string password = 3;
}

message ChangeEmailRequest {
  string email = 1;
}

message EditBalanceRequest {
  string userId = 1;
  optional double depositAmount = 2;
  optional double spentAmount = 3;
}


// Responses
message RegisterResponse {
  string msg = 1;
}

message JwtTokenResponse {
  string token = 1;
}